name: Man10KitchenGarden
version: 1.0
softdepend:
  - Man10CommonLibs
depend:
  - Man10RealEstate
main: red.man10.man10kitchengarden.Man10KitchenGarden
api-version: 1.16
commands:
  mkg:
    default: op